### ISSUE TITLE
Several fixes to mergeMarketDataR

### ISSUE THREAD

**Issue by robustport** [robustport/PCRA#5]
For example  (1) There are 3 @description tags, and (2) The Example uses a different function name than the functions itself.  The Example function name seems better, so I will create a function with that name, and with those fixes.

**Comment by spinnj** [comment]
I believe mergeMarketData.R is deprecated and should be removed. mergeCRSPandSPGMI.R should be the replacement for this.

**Comment by robustport** [comment]
This is no longer an issue.
