### ISSUE TITLE
Failure of Install Due to Error

### ISSUE THREAD

**Issue by robustport** [robustport/PCRA#6]
Error: package or namespace load failed for 'PCRA' in namespaceExport(ns, exports):
 undefined exports: mergeMarketData
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/R/R-4.2.0/library/PCRA'
* restoring previous 'C:/R/R-4.2.0/library/PCRA'

**Comment by spinnj** [comment]
Did you roxygenize the package? There seems to be a namespace entry for mergeMarketData in the NAMESPACE file, but that function no longer exists. My understanding is that roxygen should clean that up?

**Comment by robustport** [comment]
That's what I was thinking as well.  But I think I tried to roxygenize it, and it didn't work.  I will take a quick look at something, and get back to you in a few minutes,

**Comment by robustport** [comment]
The NAMESPACE entry is still there, but no mergeMarketData in either the R or man folders, so why don't you run roxygenize?  FYI, I have switched to using devtools:: document() to roxygenize.

**Comment by spinnj** [comment]
Calling roxygen2::roxygenise() directly cleaned up the namespace and the package builds fine for me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robustport** [comment]
This is no longer an issue.
