### ISSUE TITLE
Problem with selectCRSPandSPGMI

### ISSUE THREAD

**Issue by robustport** [robustport/PCRA#7]
I get the same error testing my function with selectCRSPandSPGMI, as when running the Example in the man page, namely:

Error in `[.data.frame`(x, i, j): object '..fac_sel' not found

**Comment by spinnj** [comment]
This is caused by my not structuring the code properly for data.table. I pushed a temp fix that imports data.table, which allows the function to work.

**Comment by spinnj** [comment]
I think the current version that imports data.table may be the best/easiest solution to this one.
